import { useEffect, useRef, useState } from 'react';
const projects=[
 {title:'Online Shopping Website',desc:'A full-stack e-commerce platform for products, cart management and customer orders, backed by FastAPI and MongoDB.',tags:['Python','FastAPI','MongoDB','JavaScript','REST API'],icon:'🛒',category:'fullstack',github:'https://github.com/raqeem743/Online_shopping.git'},
 {title:'URL Shortener',desc:'A URL management application that creates compact links, expands them and stores URL records with a FastAPI and MongoDB backend.',tags:['Python','FastAPI','MongoDB','JavaScript','API'],icon:'↗',category:'backend',github:'https://github.com/raqeem743/Url_Shortener.git'},
 {title:'LESCO Notice Software',desc:'A browser-automation workflow using Playwright to collect LESCO bill information and generate notice documents from the retrieved data.',tags:['Python','FastAPI','Playwright','Automation','DOCX'],icon:'▣',category:'automation',github:'https://github.com/raqeem743/Notice-softawre-using-playwright.git'},
 {title:'Todo List',desc:'A task-management application demonstrating CRUD operations, frontend interaction and backend API integration.',tags:['Python','FastAPI','JavaScript','CRUD','API'],icon:'✓',category:'fullstack',github:'https://github.com/raqeem743/todolist.git'},
];
export default function Projects(){const ref=useRef<HTMLElement>(null); const [filter,setFilter]=useState('all'); useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.querySelectorAll('.reveal').forEach((x,i)=>setTimeout(()=>{(x as HTMLElement).style.opacity='1';(x as HTMLElement).style.transform='translateY(0)'},i*90))}),{threshold:.08});if(ref.current)o.observe(ref.current);return()=>o.disconnect()},[]); const shown=filter==='all'?projects:projects.filter(p=>p.category===filter);
return <section id="projects" ref={ref} className="relative py-28 overflow-hidden"><div className="absolute inset-0 grid-pattern opacity-20"/><div className="orb w-96 h-96 bg-indigo-600/10 left-[-180px] top-20"/><div className="relative z-10 max-w-6xl mx-auto px-6"><div className="text-center mb-12"><span className="section-kicker reveal opacity-0 translate-y-8">Selected Work</span><h2 className="section-heading reveal opacity-0 translate-y-8">Projects that solve real problems.</h2><p className="section-copy reveal opacity-0 translate-y-8">A selection of applications and automation projects I have built while developing my full-stack skills.</p></div><div className="reveal opacity-0 translate-y-8 flex justify-center flex-wrap gap-2 mb-10">{[['all','All'],['fullstack','Full Stack'],['backend','Backend'],['automation','Automation']].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`filter-btn ${filter===v?'selected':''}`}>{l}</button>)}</div><div className="grid md:grid-cols-2 gap-6">{shown.map((p,i)=><article key={p.title} className="reveal opacity-0 translate-y-8 project-card" style={{transitionDelay:`${i*70}ms`}}><div className="flex justify-between items-start"><div className="project-icon">{p.icon}</div><a href={p.github} target="_blank" rel="noreferrer" className="repo-link">GitHub ↗</a></div><div className="mt-7"><span className="text-xs uppercase tracking-widest text-indigo-300">{p.category}</span><h3 className="text-2xl font-bold text-white mt-2 group-hover:text-indigo-300">{p.title}</h3><p className="text-slate-400 leading-relaxed mt-3">{p.desc}</p></div><div className="flex flex-wrap gap-2 mt-6">{p.tags.map(t=><span key={t} className="tech-tag">{t}</span>)}</div><a href={p.github} target="_blank" rel="noreferrer" className="inline-flex mt-7 text-sm font-semibold text-slate-300 hover:text-white transition">View repository <span className="ml-2 group-hover:translate-x-1">→</span></a></article>)}</div></div></section>}
